services:
  postgres-db:
    image: pgvector/pgvector:pg16
    container_name: chat-postgres-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS} 
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    # volumes:
    #   - ./data:/var/lib/postgresql/data
  
  chatdb-app:
    image: chatdb-app
    build:
      dockerfile: dockerfile.chatdb
    env_file:
      - .env
    ports:
      - "8000:8000"
      - "8051:8051"
    depends_on:
      postgres-db:
        condition: service_healthy
    restart: on-failure